### ISSUE TITLE
ItemFrame ItemDrop Bug

### ISSUE THREAD

**Issue by Prisane** [TesseractTeam/Tesseract#221]
#### Problem description

```
Notice: Uninitialized string offset: 6 in /home/xxxx/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154

Notice: Uninitialized string offset: 6 in /home/xxxx/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154

Notice: Uninitialized string offset: 6 in /home/xxxx/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154
```

anymore item is dropped out, but and i saw this message on console. I do not know why

#### OS and versions

* Tesseract: Latest commit
* PHP: 7.0.15
* Server OS: Ubuntu
* Game version: 1.0.3 
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by LordJoshie** [comment]
sooo.... is this fixed, should I test ?

**Comment by AppleDevelops** [comment]
Test please @LordJoshie, I'm busy with 1.0.4 protocols.

**Comment by LordJoshie** [comment]
Okay, testing this now as thoroughly as possible.

-Placing Enchanted/Non-Enchanted items in frame.
-Trying to pop them out. 
-Trying to break the frame with item placed in it. 

Will edit this once I'm done.

**Comment by LordJoshie** [comment]
Received the following console errors while testing. 


![capture](https://cloud.githubusercontent.com/assets/17371144/22914366/1494a656-f23e-11e6-987a-3dee43843c60.PNG)

**Comment by remotevase** [comment]
Hmm...

**Comment by Prisane** [comment]
@AppleDevelops i tested but not improved

**Comment by AppleDevelops** [comment]
Test this please :D

**Comment by remotevase** [comment]
I can't test for a while (vacation) sorry

**Comment by Prisane** [comment]
Sorry, that the problem is still going on @AppleDevelops

**Comment by Prisane** [comment]
#280 Possibly fix

**Comment by Prisane** [comment]
```
Notice: Uninitialized string offset: 6 in /home/xxxx/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154

Notice: Uninitialized string offset: 6 in /home/xxxx/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154

Notice: Uninitialized string offset: 6 in /home/xxxx/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154
```

anymore item is dropped out, but and i saw this message on console. I do not know why

**Comment by LordJoshie** [comment]
Hey... it now functions better, as it should. 

but in console we get this new error. 

Notice: Uninitialized string offset: 4 in /home/xxxx/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 171



and uh... scratch that whole "working as it should" thing... it was for a min or two, but now I went to get my item back, and it disappeared. 


but ! getting closer :)

**Comment by AppleDevelops** [comment]
Fixed

**Comment by LordJoshie** [comment]
lol.... keep testing.

I assure you, unless you JUST did something extra, it's still not fixed. 

As I said, I had my items vanish. 

Reproduce this as a random, by placing two item frames, and then putting items in/out of them... 

Eventually, you'll notice you've lost items. 

Also, my players have recently had homes/inventory cleared... probably not related, but figured I'd mention it, in case this comes up as an issue. 

May have something to do with my plugs... but I doubt it, since this only just began happening with recent changes. 

The itemframe issue tho, with vanishing items... I'd have a closer look into that. 

Unless it's just me. Someone else spend a bit more than 2 mins testing this in a server, or I'll make a video or something....

**Comment by AppleDevelops** [comment]
I assure you that it's fixed in latest commit

**Comment by LordJoshie** [comment]
Ill wait for the lil red x to go away next to this commit in commits, then
Ill test on my server.

U da bomb digitty tho.

**Comment by AppleDevelops** [comment]
It works @LordJoshie pthreads isn't tho
