### ISSUE TITLE
Still an ItemFrame Issue

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#427]
![image](https://cloud.githubusercontent.com/assets/17371144/24362751/adea0bbc-12db-11e7-96e9-c77b97b7c9db.png)

 21d033b

seems we still have an issue with the itemframes....
and when I hover over, it shows the itemname/info of my item, which is cool !

**Comment by ISRAPIL** [comment]
What???? I do not understand what you mean...

**Comment by ImagicalGamer** [comment]
The remaining item frame bug is client side. We fixed the server side bug.

**Comment by LordJoshie** [comment]
Okay, I was talking to apple about some possibilities causing the enchanted
items showing up as square tiles.

**Comment by LordJoshie** [comment]
When the dude doesn't actually know why this problem persists.... just blame Mojang.

**Comment by ImagicalGamer** [comment]
When it's a client side problem, Tesseract cannot be blamed. Therefor Mojang (the creators of MCPE) are to be blamed.

**Comment by AppleDevelops** [comment]
It isn't a client side bug 😂😂

**Comment by ImagicalGamer** [comment]
EDIT: @AppleDevelops I have a working fix of ItemFrames running on my server and what I did fixed all server side bugs.

**Comment by LordJoshie** [comment]
then share a link to your work for the rest of us to see and test.

also, thank you for your contributing work towards resolving this issue.

**Comment by TDMidkwhatisxd** [comment]
I dont think it fixed all bugs :) ! Example -> float inventory drop items stuck there! Some of my players found ways to duplicate diamonds becouse of that! Some had stacks of diamond blocks!
Wen i changed to dellete items stuck in floating inventory, glich stoped , but ppl who gliched had items removed!

And there are more and more server side bugs! A little code cant fix them all!
