### ISSUE TITLE
Could not tick level "level-name": Call to a member function getValue() on null

### ISSUE THREAD

**Issue by Dhrhciebcy** [TesseractTeam/Tesseract#81]
#### Issue description
It locks some worlds and it's very repetitive

#### Steps to reproduce the issue
Before start the server, insert a new world from minecraf 1.9 (computer's minecraft), then start the server and enter in this new world 

#### OS and versions
* Tesseract: 1.2.0 
* PHP:
* Server OS: Windows 10 Pro
* Game version: 1.1.0.55

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)
Tesseract >
┌─────────────────────────────────────────────────┐  -- Loaded: Properties and Configuration --
│                                                 │    Date: Fri, July 07, 2017, 19:28 BST
│   _______                                _      │    Version: 1.2.0 Codename: Ruby
│  |__   __|                              | |     │    MCPE: v1.1.0.55 Protocol: 113
│     | | ___  ___ ___  ___ _ __ __ _  ___| |_    │    IP: 2.232.186.251 Port: 19132
│     | |/ _ \/ __/ __|/ _ \ '__/ _` |/ __| __|   │    Query: 0.0.0.0
│     | |  __/\__ \__ \  __/ | | (_| | (__| |_    │    SSL Extension: true
│     |_|\___||___/___/\___|_|  \__,_|\___|\__|   │    Authentication: online mode/secure
│                                                 │  ------------------------------------------
│                                                 │    API Version: 3.0.1
│   Support: github.com/TesseractTeam/Tesseract   │    Language: ita
│                                                  │    Package: phar
└─────────────────────────────────────────────────┘  ------------------------------------------
Tesseract > Starting remote control listener
Tesseract > RCON running on 0.0.0.0:19132
Tesseract > Everything seems to be alright! Server started!
Tesseract > Loading recipes...
Tesseract > Loading aFloatingText v1.2
Tesseract > Loading ColorMatch v1.1.1
Tesseract > Loading EconomyAPI v2.0.9
Tesseract > Loading EconomyAuction v2.0.2
Tesseract > Loading EconomyCasino v2.0.2
Tesseract > Loading EconomyJob v2.0.4
Tesseract > Loading EconomyLand v2.0.9
Tesseract > Loading EconomyPShop v2.0.2
Tesseract > Loading EconomySell v2.0.7
Tesseract > Loading EconomyShop v2.0.7
Tesseract > Loading EconomyTax v2.0.3
Tesseract > Loading EconomyUsury v1.0.1
Tesseract > Loading ManyWorlds v2.0.3
Tesseract > Loading NPC v1.4
Tesseract > Could not load plugin 'PlayNoteBlockSong': Unknown dependency
Tesseract > Loading ClearLagg v1.1.0
Tesseract > Loading TapToDo v2.2.1
Tesseract > Loading WhitelistReason v2.2.0
Tesseract > Loading SignPortal v1.1.2
Tesseract > Loading Alias v1.2.0
Tesseract > Loading RealTime v2.1.1
Tesseract > Loading DevTools v1.10.0
Tesseract > Loading MSpawns v1.5
Tesseract > Loading iProtector v3.1b
Tesseract > Loading FactionsPro v1.3.2
Tesseract > Loading ServerAuth v2.11
Tesseract > Loading WorldEdit+ v0.01
Tesseract > Loading plugin: AreaProtect v1.0.1
Tesseract > Loading plugin: SW_svile v0.6dev
Tesseract > Loading EconomyAirport v2.0.4
Tesseract > Could not load plugin 'PlayNoteBlockSong': Unknown dependency
Tesseract > Could not load plugin 'PlayNoteBlockSong': Unknown dependency
Tesseract > Loading BattleKits v1.0.4
Tesseract > Loading plugin: MyPlot v1.1.0
Tesseract > Could not load plugin 'PlayNoteBlockSong': Unknown dependency
Tesseract > Could not load plugin 'PlayNoteBlockSong': Circular dependency detected
Tesseract > Enabling DevTools v1.10.0
Tesseract > Could not load plugin 'AreaProtect': plugin exists
Tesseract > Could not load plugin 'MyPlot': plugin exists
Tesseract > Could not load plugin 'SW_svile': plugin exists
Tesseract > [DevTools] Registered folder plugin loader
Tesseract > Enabling MSpawns v1.5
Tesseract > Enabling ServerAuth v2.11
Tesseract > Enabling SW_svile v0.6dev
Tesseract > Level "hypixel1" not found
Tesseract > Level "Minigiochi" not found
Tesseract > Level "nether sw" not found
Tesseract > Level "Minigiochi" not found
Tesseract > Level "spazio" not found
Tesseract > Level "Minigiochi" not found
Tesseract > Level "gravity" not found
Tesseract > Level "Minigiochi" not found
Tesseract > [SW_svile]

*****************************************************
Author: svile
Kik: _svile_
Telegram_Group: https://telegram.me/svile
E-mail: thesville@gmail.com
Github: https://github.com/svilex/SkyWars-PocketMine
SkyWars plugin by svile: ENABLED
*****************************************************

Tesseract > Enabling MyPlot v1.1.0
Tesseract > [MyPlot] Loading MyPlot
Tesseract > Preparing level "Hub"
Tesseract > Preparing level "nether"
Tesseract > Enabling aFloatingText v1.2
Tesseract > [aFloatingText] Плагин загружен
Tesseract > Enabling ColorMatch v1.1.1
Tesseract > Selected language English
Tesseract > [ColorMatch] checking arena files...
Tesseract > Preparing level "ColorMatch"
Tesseract > Spawn terrain for level "ColorMatch" is being generated in the background
Tesseract > [ColorMatch] ColorMatch enabled
Tesseract > Enabling EconomyAPI v2.0.9
Tesseract > [EconomyAPI] Auto save has been set to interval : 10 min(s)
Tesseract > [EconomyAPI] Checking for updates... It may be take some while.
Tesseract > Enabling EconomyAuction v2.0.2
Tesseract > Enabling EconomyCasino v2.0.2
Tesseract > Enabling EconomyJob v2.0.4
Tesseract > Enabling EconomyLand v2.0.9
Tesseract > Enabling EconomyPShop v2.0.2
Tesseract > [EconomyPShop] [DEPENDENCY] Please install ItemCloud plugin to use PShop plugin.
Tesseract > Enabling EconomySell v2.0.7
Tesseract > Enabling EconomyShop v2.0.7
Tesseract > Enabling EconomyTax v2.0.3
Tesseract > Enabling EconomyUsury v1.0.1
Tesseract > Enabling ManyWorlds v2.0.3
Tesseract > Enabling NPC v1.4
Tesseract > Enabling ClearLagg v1.1.0
Tesseract > Enabling TapToDo v2.2.1
Tesseract > Enabling WhitelistReason v2.2.0
Tesseract > Enabling SignPortal v1.1.2
Tesseract > Enabling Alias v1.2.0
Tesseract > Enabling RealTime v2.1.1
Tesseract > [RealTime] RealTime enabled.
Tesseract > [RealTime] [RealTime] It is 19 (20h is same as 8pm)
Tesseract > [RealTime] 6000
Tesseract > Enabling iProtector v3.1b
Tesseract > Enabling FactionsPro v1.3.2
Tesseract > Enabling WorldEdit+ v0.01
Tesseract > Enabling AreaProtect v1.0.1
Tesseract > [AreaProtect] AreaProtect Loaded!
Tesseract > Enabling EconomyAirport v2.0.4
Tesseract > Enabling BattleKits v1.0.4
Tesseract > [BattleKits] Loaded EconomyS by onebone
Tesseract > [BattleKits] Loaded 1 kits.
Tesseract > Starting GS4 status listener
Tesseract > Query running on 0.0.0.0:19132
Tesseract > Default game type: Survival Mode
Tesseract > Done (5.285s)! For help, type "help" or "?"
Tesseract > Dhrhciebcy[/192.168.1.101:45376] [ClientID: -265199910979812492] logged in with entity id 1 at (Hub, 56.1814, 77.7883, 364.6297)
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract> Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null

Tesseract > Dhrhciebcy[/192.168.1.101:45376] logged out due to timeout

Tesseract > [CONSOLE: Stopping the server]
Tesseract > Could not tick level "Hub": Call to a member function getValue() on null
Tesseract > Disabling aFloatingText v1.2
Tesseract > [aFloatingText] Плагин выгружен
Tesseract > Disabling ColorMatch v1.1.1
Tesseract > [ColorMatch] ColorMatch disabled
Tesseract > Disabling EconomyAPI v2.0.9
Tesseract > Disabling EconomyAuction v2.0.2
Tesseract > Disabling EconomyCasino v2.0.2
Tesseract > Disabling EconomyJob v2.0.4
Tesseract > Disabling EconomyLand v2.0.9
Tesseract > Disabling EconomyPShop v2.0.2
Tesseract > Disabling EconomySell v2.0.7
Tesseract > Disabling EconomyShop v2.0.7
Tesseract > Disabling EconomyTax v2.0.3
Tesseract > Disabling EconomyUsury v1.0.1
Tesseract > Disabling ManyWorlds v2.0.3
Tesseract > Disabling NPC v1.4
Tesseract > Disabling ClearLagg v1.1.0
Tesseract > Disabling TapToDo v2.2.1
Tesseract > [TapToDo] Saving blocks...
Tesseract > Disabling WhitelistReason v2.2.0
Tesseract > Disabling SignPortal v1.1.2
Tesseract > Disabling Alias v1.2.0
Tesseract > Disabling RealTime v2.1.1
Tesseract > [RealTime] RealTime disabled.
Tesseract > Disabling DevTools v1.10.0
Tesseract > Disabling MSpawns v1.5
Tesseract > Disabling iProtector v3.1b
Tesseract > Disabling FactionsPro v1.3.2
Tesseract > Disabling ServerAuth v2.11
Tesseract > Disabling WorldEdit+ v0.01
Tesseract > Disabling AreaProtect v1.0.1
Tesseract > Disabling SW_svile v0.6dev
Tesseract > Preparing level "hypixel1"
Tesseract > Unloading level "hypixel1"
Tesseract > Preparing level "hypixel1"
Tesseract > Unloading level "hypixel1"
Tesseract > Preparing level "hypixel1"
Tesseract > Level "Minigiochi" not found
Tesseract > Preparing level "nether sw"
Tesseract > Unloading level "nether sw"
Tesseract > Preparing level "nether sw"
Tesseract > Unloading level "nether sw"
Tesseract > Preparing level "nether sw"
Tesseract > Level "Minigiochi" not found
Tesseract > Preparing level "spazio"
Tesseract > Unloading level "spazio"
Tesseract > Preparing level "spazio"
Tesseract > Unloading level "spazio"
Tesseract > Preparing level "spazio"
Tesseract > Level "Minigiochi" not found
Tesseract > Preparing level "gravity"
Tesseract > Unloading level "gravity"
Tesseract > Preparing level "gravity"
Tesseract > Unloading level "gravity"
Tesseract > Preparing level "gravity"
Tesseract > Level "Minigiochi" not found
Tesseract > Disabling EconomyAirport v2.0.4
Tesseract > Disabling BattleKits v1.0.4
Tesseract > Disabling MyPlot v1.1.0
Tesseract > Unloading level "Hub"
Tesseract > Unloading level "nether"
Tesseract > Unloading level "ColorMatch"
Tesseract > Unloading level "hypixel1"
Tesseract > Unloading level "nether sw"
Tesseract > Unloading level "spazio"
Tesseract > Unloading level "gravity"
Tesseract > Stopping other threads
Tesseract > 4 threads has stopped
Tesseract > Server has stopped
bin\php\php.exe: Exit 1.

```
```

**Comment by xZeroMCPE** [comment]
Which branch?

**Comment by xISRAPILx** [comment]
master @xZeroMCPE

**Comment by Dhrhciebcy** [comment]
"Which branch?"


What do you want to know exactly?

**Comment by ariefbayu** [comment]
Maybe this is the cause:

`Before start the server, insert a new world from minecraf 1.9 (computer's minecraft), then start the server and enter in this new world`

From my understanding, Tesseract is for Minecraft PE. There could be a different data structure between world from PE and from PC.

**Comment by Dhrhciebcy** [comment]
But I have in my server a lot of worlds from MCPC and there aren't problems with them

**Comment by Dhrhciebcy** [comment]
Because I had a lot of MCPC's worlds before use Tesseract. I used genisys and there weren't problems like this with Tesseract

**Comment by NickTehUnicorn** [comment]
This is because you disabled mobs/animals and there are animals in the map you've imported from MCPC. Luckily, there is a plugin fix for this. Load the plugin below, and run the command "/clearlagg clearall" and it should be fixed.

http://forums.pocketmine.net/plugins/clearlagg.1116/

**Comment by Dhrhciebcy** [comment]
Fix only 50%
The plugin works, but the bug remains. After I have written the command in the world, I move my player and there is the bug again

**Comment by NickTehUnicorn** [comment]
It's because your server is loading new chunks with mobs in them.

Just run the command again!

**Comment by Dhrhciebcy** [comment]
Yes, I know, but is very boring and I have also worlds with mobs inside without problems

**Comment by Rateek** [comment]
fix https://github.com/TesseractTeam/Tesseract/commit/e895c7403faa8fe0ecbb235ed6c0c17504f3410f
